import io
import os
import cv2
import uuid
import base64
import numpy as np
from PIL import Image, ImageChops, ImageStat, ImageEnhance
from dotenv import load_dotenv
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import json
import asyncio
import logging
from typing import Literal, List, Optional, Any

logger = logging.getLogger(__name__)
from fastapi.responses import StreamingResponse

from google import genai
from google.genai import types
from google.cloud import firestore
from google.cloud import storage

load_dotenv()

PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "ai-forensics-project-4421")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
CEREBRAS_API_KEY = os.environ.get("CEREBRAS_API_KEY")

if GEMINI_API_KEY:
    client = genai.Client(
        api_key=GEMINI_API_KEY, http_options={"api_version": "v1beta"}
    )
else:
    logger.warning("GEMINI_API_KEY not found in environment.")
    client = None

# Initialize Firestore DB
try:
    db = firestore.Client(project=PROJECT_ID)
except Exception as e:
    logger.warning(f"Failed to initialize Firestore: {e}")
    db = None

# Initialize GCS
try:
    storage_client = storage.Client(project=PROJECT_ID)
    BUCKET_NAME = f"{PROJECT_ID}-evidence"
    bucket = storage_client.bucket(BUCKET_NAME)
    if not bucket.exists():
        bucket = storage_client.create_bucket(BUCKET_NAME, location=LOCATION)
        # Auto-delete evidence files after 7 days to prevent runaway storage costs
        bucket.add_lifecycle_delete_rule(age=7)
        bucket.patch()
except Exception as e:
    logger.warning(f"Failed to initialize GCS: {e}")
    storage_client = None

# Increase upload size limit to 50MB (fixes 413 Entity Too Large in newer Starlette versions)
import starlette.formparsers

starlette.formparsers.MultiPartParser.max_file_size = 1024 * 1024 * 50

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "https://*.vercel.app",
        "https://ai-image-forensics-app.vercel.app"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ReasoningStep(BaseModel):
    thought: str
    action: Optional[str] = None
    observation: Optional[str] = None


class ForensicFinding(BaseModel):
    description: str
    location_normalized: list[int]  # [ymin, xmin, ymax, xmax] from 0-1000


class ForensicEvidence(BaseModel):
    name: str
    url: str  # Base64 data URL


class ForensicAnalysisResult(BaseModel):
    case_id: Optional[str] = None
    verdict: str
    confidence_level: str
    explanation: str
    detailed_findings: list[ForensicFinding] = []
    evidence_images: list[ForensicEvidence] = []
    reasoning_steps: list[ReasoningStep] = []


def get_ela_image(original_pil: Image.Image, quality: int = 90) -> bytes:
    """Generates an Error Level Analysis (ELA) image."""
    temp_buf = io.BytesIO()
    original_pil.save(temp_buf, format="JPEG", quality=quality)
    temp_buf.seek(0)
    temp_img = Image.open(temp_buf)
    ela_img = ImageChops.difference(original_pil, temp_img)
    ela_img = ImageEnhance.Brightness(ela_img).enhance(20.0)
    res_buf = io.BytesIO()
    ela_img.save(res_buf, format="JPEG")
    return res_buf.getvalue()


def get_corner_zoom(original_pil: Image.Image, size: int = 300) -> bytes:
    """Provides a high-res crop of the bottom-right corner."""
    w, h = original_pil.size
    corner = original_pil.crop((w - size, h - size, w, h))
    buf = io.BytesIO()
    corner.save(buf, format="JPEG", quality=100)
    return buf.getvalue()


def get_edge_map(image_bytes: bytes) -> bytes:
    """Generates a Canny Edge map to highlight geometric artifacts."""
    nparr = np.frombuffer(image_bytes, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_GRAYSCALE)
    edges = cv2.Canny(img, 100, 200)
    res_buf = io.BytesIO()
    is_success, buffer = cv2.imencode(".jpg", edges)
    return buffer.tobytes()


def scan_metadata(img: Image.Image) -> str | None:
    """Scans image metadata for common AI signatures."""
    metadata_str = str(img.info).lower()
    ai_keywords = [
        "gemini",
        "dall-e",
        "midjourney",
        "stable diffusion",
        "adobe firefly",
        "generated by ai",
        "ai-generated",
    ]
    for word in ai_keywords:
        if word in metadata_str:
            return f"Found AI signature in metadata: '{word}'"
    return None


def upload_to_gcs(
    image_bytes: bytes, filename: str, content_type: str = "image/jpeg"
) -> str:
    """Uploads bytes to GCS and returns the public URL."""
    if storage_client is None:
        # Fallback to local Base64 for local dev without GCS
        return f"data:{content_type};base64,{base64.b64encode(image_bytes).decode()}"
    try:
        blob = bucket.blob(filename)
        blob.upload_from_string(image_bytes, content_type=content_type)
        # Assuming the bucket is configured for public read access. If not, this URL will 403.
        return f"https://storage.googleapis.com/{BUCKET_NAME}/{filename}"
    except Exception as e:
        logger.error(f"GCS Upload Error: {e}")
        return ""


from services.provider_router import PROVIDER_STATUS, check_provider_health


@app.on_event("startup")
async def startup_event():
    import asyncio

    asyncio.create_task(check_provider_health("gemini"))
    asyncio.create_task(check_provider_health("groq"))
    asyncio.create_task(check_provider_health("cerebras"))


@app.get("/")
def read_root():
    return {"status": "Forensic Agent Online", "project": PROJECT_ID}


@app.get("/health")
async def health():
    return {"providers": PROVIDER_STATUS}


MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"]


@app.post("/analyze_image/")
async def analyze_image(file: UploadFile = File(...)):
    if file.content_type not in ALLOWED_MIME_TYPES:
        raise HTTPException(
            status_code=415,
            detail="Unsupported file format. Please upload a JPEG, PNG, or WEBP.",
        )

    image_bytes = await file.read()
    if len(image_bytes) > MAX_FILE_SIZE:
        raise HTTPException(status_code=413, detail="File exceeds the 5MB size limit.")

    queue = asyncio.Queue()

    async def send_event(data: dict):
        await queue.put(f"data: {json.dumps(data)}\n\n")

    async def analysis_task():
        try:
            pil_img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
            case_id = f"FF-{str(uuid.uuid4())[:8].upper()}"
            evidence_images = []

            metadata_finding = scan_metadata(pil_img)

            ela_bytes = get_ela_image(pil_img)
            ela_url = upload_to_gcs(ela_bytes, f"{case_id}-global-ela.jpg")
            evidence_images.append(
                ForensicEvidence(name="Global Error Level Analysis (ELA)", url=ela_url)
            )

            edge_bytes = get_edge_map(image_bytes)
            edge_url = upload_to_gcs(edge_bytes, f"{case_id}-edge-map.jpg")
            evidence_images.append(
                ForensicEvidence(name="Edge Detection Map", url=edge_url)
            )

            await send_event(
                {"stage": "cv_complete", "message": "ELA map and edge detection ready"}
            )

            await send_event(
                {
                    "stage": "agent_a_thinking",
                    "message": "Metadata analyst examining compression layers...",
                }
            )
            await send_event(
                {
                    "stage": "agent_b_thinking",
                    "message": "Geometric auditor scanning for plausibility failures...",
                }
            )

            from services.provider_router import run_vision_agents

            metadata = {
                "format": getattr(pil_img, "format", "Unknown"),
                "size": pil_img.size,
                "mode": pil_img.mode,
            }
            if metadata_finding:
                metadata["scan_result"] = metadata_finding

            report_a, report_b = await run_vision_agents(
                image_bytes, ela_bytes, edge_bytes, metadata
            )

            await send_event(
                {
                    "stage": "agents_complete",
                    "message": "Both specialists have filed their reports",
                }
            )

            await send_event(
                {
                    "stage": "arbitration_start",
                    "message": "Arbitrator weighing the evidence...",
                }
            )

            from services.agent_c import run_agent_c

            final_verdict = await run_agent_c(report_a, report_b)

            # Persist to Firestore
            if db is not None:
                try:
                    orig_url = upload_to_gcs(
                        image_bytes, f"{case_id}-original.jpg", file.content_type
                    )
                    doc_data = {
                        "case_id": case_id,
                        "verdict": final_verdict.verdict,
                        "confidence": final_verdict.confidence,
                        "final_verdict_data": final_verdict.model_dump(),
                        "evidence_images": [
                            img.model_dump() for img in evidence_images
                        ],
                        "original_image_url": orig_url,
                        "created_at": firestore.SERVER_TIMESTAMP,
                    }
                    db.collection("forensic_cases").document(case_id).set(doc_data)
                except Exception as e:
                    logger.error(f"Error saving to Firestore: {e}")

            payload_data = final_verdict.model_dump()
            payload_data["case_id"] = case_id
            payload_data["evidence_images"] = [
                img.model_dump() for img in evidence_images
            ]
            try:
                payload_data["original_image_url"] = orig_url
            except NameError:
                pass

            await send_event({"stage": "verdict_ready", "payload": payload_data})

        except Exception as e:
            logger.error(f"Error in analysis task: {e}")
            await send_event({"stage": "error", "message": str(e)})
        finally:
            await queue.put(None)

    async def generator():
        task = asyncio.create_task(analysis_task())
        while True:
            item = await queue.get()
            if item is None:
                break
            yield item
        await task

    return StreamingResponse(
        generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@app.get("/cases/{case_id}", response_model=ForensicAnalysisResult)
def get_case(case_id: str):
    if db is None:
        raise HTTPException(status_code=503, detail="Database not initialized.")

    doc_ref = db.collection("forensic_cases").document(case_id)
    doc = doc_ref.get()

    if not doc.exists:
        raise HTTPException(status_code=404, detail="Case not found")

    data = doc.to_dict()

    # Reconstruct perfectly
    return ForensicAnalysisResult(
        case_id=data.get("case_id", case_id),
        verdict=data.get("verdict", "Unknown"),
        confidence_level=data.get("confidence_level", "Low"),
        explanation=data.get("explanation", ""),
        detailed_findings=[
            ForensicFinding(**f) for f in data.get("detailed_findings", [])
        ],
        evidence_images=[
            ForensicEvidence(**img) for img in data.get("evidence_images", [])
        ],
        reasoning_steps=[],
    )
