import io
import os
import cv2
import numpy as np
from PIL import Image, ImageChops, ImageStat, ImageEnhance
from dotenv import load_dotenv
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Literal
from google import genai
from google.genai import types

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ForensicFinding(BaseModel):
    description: str
    location_normalized: list[int] # [ymin, xmin, ymax, xmax] from 0-1000

class ForensicEvidence(BaseModel):
    name: str
    url: str # Base64 data URL

class ForensicAnalysisResult(BaseModel):
    verdict: str
    confidence_level: str
    explanation: str
    detailed_findings: list[ForensicFinding] = []
    evidence_images: list[ForensicEvidence] = []

def get_ela_image(original_pil: Image.Image, quality: int = 90) -> bytes:
    """Generates an Error Level Analysis (ELA) image."""
    # 1. Save original as a temporary JPEG with specific quality
    temp_buf = io.BytesIO()
    original_pil.save(temp_buf, format="JPEG", quality=quality)
    temp_buf.seek(0)
    
    # 2. Re-open the temporary JPEG
    temp_img = Image.open(temp_buf)
    
    # 3. Calculate absolute difference
    ela_img = ImageChops.difference(original_pil, temp_img)
    
    # 4. Enhance the difference using a FIXED 20x multiplier to prevent washing out subtle artifacts
    ela_img = ImageEnhance.Brightness(ela_img).enhance(20.0)
    
    # 5. Return as JPEG bytes
    res_buf = io.BytesIO()
    ela_img.save(res_buf, format="JPEG")
    return res_buf.getvalue()

def get_corner_zoom(original_pil: Image.Image, size: int = 300) -> bytes:
    """Provides a high-res crop of the bottom-right corner."""
    w, h = original_pil.size
    # Focus strictly on the bottom-right 300x300 corner
    corner = original_pil.crop((w - size, h - size, w, h))
    buf = io.BytesIO()
    corner.save(buf, format="JPEG", quality=100) # Uncompressed for maximum detail
    return buf.getvalue()

def get_edge_map(image_bytes: bytes) -> bytes:
    """Generates a Canny Edge map to highlight geometric artifacts."""
    nparr = np.frombuffer(image_bytes, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_GRAYSCALE)
    # Detect edges - low/high thresholds tuned for watermark detection
    edges = cv2.Canny(img, 100, 200)
    res_buf = io.BytesIO()
    is_success, buffer = cv2.imencode(".jpg", edges)
    return buffer.tobytes()

def scan_metadata(img: Image.Image) -> str | None:
    """Scans image metadata for common AI signatures."""
    metadata_str = str(img.info).lower()
    ai_keywords = ["gemini", "dall-e", "midjourney", "stable diffusion", "adobe firefly", "generated by ai", "ai-generated"]
    for word in ai_keywords:
        if word in metadata_str:
            return f"Found AI signature in metadata: '{word}'"
    return None

@app.get("/")
def read_root():
    return {"status": "Backend is Online", "CORS": "Active"}

@app.post("/analyze_image/", response_model=ForensicAnalysisResult)
async def analyze_image(file: UploadFile = File(...)):
    try:
        # 1. Read the original image
        image_bytes = await file.read()
        pil_img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        width, height = pil_img.size
        
        # 2. QUICK SCAN: Metadata Forensics
        metadata_finding = scan_metadata(pil_img)
        if metadata_finding:
            return ForensicAnalysisResult(
                verdict="AI-Generated",
                confidence_level="High",
                explanation=f"HARD-CODED DETECTION: {metadata_finding}. This image contains explicit digital watermarks in its file header.",
                detailed_findings=[ForensicFinding(description=metadata_finding, location_normalized=[0,0,0,0])]
            )
        
        # 3. Generate 4 Quadrants (Sliding Window)
        mid_x, mid_y = width // 2, height // 2
        quadrants = [
            pil_img.crop((0, 0, mid_x, mid_y)),          # Top-Left
            pil_img.crop((mid_x, 0, width, mid_y)),      # Top-Right
            pil_img.crop((0, mid_y, mid_x, height)),     # Bottom-Left
            pil_img.crop((mid_x, mid_y, width, height)), # Bottom-Right
        ]
        
        # 4. Generate ELA, Corner Zoom, and Edge Map
        ela_bytes = get_ela_image(pil_img)
        corner_bytes = get_corner_zoom(pil_img)
        edge_bytes = get_edge_map(corner_bytes)
        
        # 5. Convert all parts to bytes for Gemini
        analysis_parts = []
        analysis_parts.append(types.Part.from_bytes(data=image_bytes, mime_type=file.content_type))
        
        for q in quadrants:
            buf = io.BytesIO()
            q.save(buf, format="JPEG", quality=95)
            analysis_parts.append(types.Part.from_bytes(data=buf.getvalue(), mime_type="image/jpeg"))
            
        analysis_parts.append(types.Part.from_bytes(data=ela_bytes, mime_type="image/jpeg"))
        analysis_parts.append(types.Part.from_bytes(data=corner_bytes, mime_type="image/jpeg")) # Image 7
        analysis_parts.append(types.Part.from_bytes(data=edge_bytes, mime_type="image/jpeg"))   # Image 8
        
        prompt = (
            "ACT AS A SENIOR HYBRID FORENSIC ANALYST. Your mission is to find PROOF of non-organic imagery. "
            "\nYou are receiving 8 forensic context images: "
            "\n- Image 1: GLOBAL CONTEXT (Full Scan)"
            "\n- Images 2-5: QUADRANT ZOOM-INS (Texture Analysis)"
            "\n- Image 6: ERROR LEVEL ANALYSIS (ELA) MAP (Intensity Check)"
            "\n- Image 7: CORNER ZOOM (High-Res Signature Scan)"
            "\n- Image 8: EDGE MAP (Canny Analysis) (Geometric Signature Scan)"
            "\n\nYOUR MISSION: Use a two-track detection system: "
            "\n\nTRACK 1: SIGNATURE SCAN (PRIORITY 0): "
            "\n- Search Image 7 and Image 8 specifically for AI 'Digital Stamps' (Monograms). These are NOT artistic decorations; they are absolute proof. "
            "\n- Look for the 'GEMINI SPARKLE' (a four-pointed star), 'DALL-E' (5 colored squares), or 'ADOBE CR' badge. "
            "\n- If a geometric shape in Image 8 matches these, you have found proof. "
            "\n\nTRACK 2: SCIENTIFIC INTEGRITY: "
            "\n1. GEOMETRIC INTEGRITY: (Images 2-5) Check for warped lines, symmetrical failures, and rigid-body fusions. "
            "\n2. TEXTURE CONTINUITY: Look for 'tiled' repetition in natural patterns, noise floor gaps, and 'plastic' smoothing. "
            "\n3. PHYSICS & LIGHTING BALANCE: (Image 1) Shadow directions, perspective consistency, and gravity logic. "
            "\n\nTHE 'ONE PROOF' RULE: If either Track 1 (Signature) or Track 2 (Physics) provides even ONE definitive failure, the image IS 'AI-Generated'. "
            "\n\nREPORT STYLE: For every finding in 'detailed_findings', explain if it is a 'Signature' or a 'Logic Failure'. Use [ymin, xmin, ymax, xmax] coordinates."
        )
        
        # Collect Evidence Images for Frontend Gallery
        import base64
        evidence_images = []
        
        # Helper to convert PIL to Base64
        def to_b64(img, name):
            b = io.BytesIO()
            img.save(b, format="JPEG", quality=85)
            b64 = base64.b64encode(b.getvalue()).decode()
            return ForensicEvidence(**{"name": name, "url": f"data:image/jpeg;base64,{b64}"})

        evidence_images.append(to_b64(Image.open(io.BytesIO(ela_bytes)), "Error Level Analysis (ELA)"))
        evidence_images.append(to_b64(Image.open(io.BytesIO(corner_bytes)), "High-Res Corner Zoom"))
        evidence_images.append(to_b64(Image.open(io.BytesIO(edge_bytes)), "Canny Edge Analysis"))
        
        # Add Quadrants
        for i, q in enumerate(quadrants):
            evidence_images.append(to_b64(q, f"Quadrant Zoom {i+1}"))

        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[prompt] + analysis_parts,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=ForensicAnalysisResult,
            ),
        )
        
        result = ForensicAnalysisResult.model_validate_json(response.text)
        result.evidence_images = evidence_images
        return result
    except Exception as e:
        print(f"Error: {e}")
        error_msg = str(e)
        if "429" in error_msg:
            raise HTTPException(status_code=429, detail="AI Resource Exhausted. Please wait a minute.")
        raise HTTPException(status_code=500, detail=error_msg)